import type { RouteObject } from 'react-router-dom'
import { Navigate } from 'react-router-dom'
import { AuthLayout } from '../layouts/AuthLayout'
import { DashboardLayout } from '../layouts/DashboardLayout'
import {
  LoginPage,
  DashboardPage,
  ContactListPage,
  ContactDetailPage,
  ContactCreatePage,
  LeadListPage,
  LeadDetailPage,
  LeadCreatePage,
  ProposalListPage,
  ProposalDetailPage,
  ProposalCreatePage,
  VisitListPage,
  VisitDetailPage,
  VisitCreatePage,
  CalendarPage,
  PipelinePage,
  AgentPage,
  ActivityListPage,
  ActivityDetailPage,
  TaskListPage,
  TaskDetailPage,
  CompanyListPage,
  CompanyDetailPage,
  CompanyEditPage,
  OpportunityListPage,
  OpportunityCreatePage,
  OpportunityDetailPage,
  AdminPage,
  AdminUsersPage,
  AdminAuditPage,
  AdminSettingsPage,
  AdminPermissionsPage,

} from './lazy-imports'

export const routes: RouteObject[] = [
  {
    path: '/login',
    element: <AuthLayout />,
    children: [
      { index: true, element: <LoginPage /> },
    ],
  },
  {
    path: '/',
    element: <DashboardLayout />,
    children: [
      { index: true, element: <Navigate to="/dashboard" replace /> },
      { path: 'dashboard', element: <DashboardPage /> },
      { path: 'contacts', element: <ContactListPage /> },
      { path: 'contacts/new', element: <ContactCreatePage /> },
      { path: 'contacts/:id', element: <ContactDetailPage /> },
      { path: 'activities', element: <ActivityListPage /> },
      { path: 'activities/:id', element: <ActivityDetailPage /> },
      { path: 'tasks', element: <TaskListPage /> },
      { path: 'tasks/:id', element: <TaskDetailPage /> },
      { path: 'companies', element: <CompanyListPage /> },
      { path: 'companies/:id/edit', element: <CompanyEditPage /> },
      { path: 'companies/:id', element: <CompanyDetailPage /> },
      { path: 'opportunities', element: <OpportunityListPage /> },
      { path: 'opportunities/new', element: <OpportunityCreatePage /> },
      { path: 'opportunities/:id', element: <OpportunityDetailPage /> },
      { path: 'leads', element: <LeadListPage /> },
      { path: 'leads/new', element: <LeadCreatePage /> },
      { path: 'leads/:id', element: <LeadDetailPage /> },
      { path: 'proposals', element: <ProposalListPage /> },
      { path: 'proposals/new', element: <ProposalCreatePage /> },
      { path: 'proposals/:id', element: <ProposalDetailPage /> },
      { path: 'technical-visits', element: <VisitListPage /> },
      { path: 'technical-visits/new', element: <VisitCreatePage /> },
      { path: 'technical-visits/:id', element: <VisitDetailPage /> },
      { path: 'calendar', element: <CalendarPage /> },
      { path: 'pipeline', element: <PipelinePage /> },
      { path: 'agent', element: <AgentPage /> },
      { path: 'admin', element: <AdminPage /> },
      { path: 'admin/users', element: <AdminUsersPage /> },
      { path: 'admin/audit', element: <AdminAuditPage /> },
      { path: 'admin/settings', element: <AdminSettingsPage /> },
      { path: 'admin/permissions', element: <AdminPermissionsPage /> },

    ],
  },
  {
    path: '*',
    element: <Navigate to="/dashboard" replace />,
  },
]
