"""initial crm schema."""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "c83462d83061"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "SALES", "MANAGER", name="userrole"),
            nullable=False,
        ),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("role IN ('ADMIN', 'SALES', 'MANAGER')", name=op.f("ck_user_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "promoter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name=op.f("fk_promoter_owner_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promoter")),
    )
    with op.batch_alter_table("promoter", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_promoter_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_promoter_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "stage_transition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum("LEAD", "PROPOSAL", name="pipelineentitytype"),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("from_stage", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
        sa.Column("to_stage", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("transitioned_by", sa.Integer(), nullable=False),
        sa.Column("transitioned_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
        sa.CheckConstraint(
            "entity_type IN ('LEAD', 'PROPOSAL')",
            name=op.f("ck_stage_transition_entity_type"),
        ),
        sa.ForeignKeyConstraint(
            ["transitioned_by"],
            ["user.id"],
            name=op.f("fk_stage_transition_transitioned_by_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_transition")),
    )
    with op.batch_alter_table("stage_transition", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stage_transition_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            "ix_stage_transition_entity_time",
            ["entity_type", "entity_id", "transitioned_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stage_transition_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stage_transition_transitioned_at"),
            ["transitioned_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stage_transition_transitioned_by"),
            ["transitioned_by"],
            unique=False,
        )
        batch_op.create_index(
            "ix_stage_transition_user_time",
            ["transitioned_by", "transitioned_at", "id"],
            unique=False,
        )

    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("INDIVIDUAL", "COMPANY", name="contacttype"), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("address_line", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
        sa.Column("promoter_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("type IN ('INDIVIDUAL', 'COMPANY')", name=op.f("ck_contact_type")),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name=op.f("fk_contact_owner_id_user")),
        sa.ForeignKeyConstraint(
            ["promoter_id"],
            ["promoter.id"],
            name=op.f("fk_contact_promoter_id_promoter"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    with op.batch_alter_table("contact", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contact_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_contact_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_contact_promoter_id"), ["promoter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_contact_type"), ["type"], unique=False)

    op.create_table(
        "company_contact_person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_contact_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("position", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_contact_id"],
            ["contact.id"],
            name=op.f("fk_company_contact_person_company_contact_id_contact"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_contact_person")),
    )
    with op.batch_alter_table("company_contact_person", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_company_contact_person_company_contact_id"),
            ["company_contact_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_company_contact_person_email"), ["email"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_company_contact_person_name"), ["name"], unique=False)

    op.create_table(
        "company_contact_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("industry", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_company_contact_profile_contact_id_contact"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_contact_profile")),
    )
    with op.batch_alter_table("company_contact_profile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_company_contact_profile_contact_id"),
            ["contact_id"],
            unique=True,
        )

    op.create_table(
        "individual_contact_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_individual_contact_profile_contact_id_contact"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_individual_contact_profile")),
    )
    with op.batch_alter_table("individual_contact_profile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_individual_contact_profile_contact_id"),
            ["contact_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_individual_contact_profile_email"), ["email"], unique=False
        )

    op.create_table(
        "lead",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "interest_type",
            sa.Enum("PHOTOVOLTAIC", "BESS", "HIBRID", name="leadinteresttype"),
            nullable=False,
        ),
        sa.Column("qualification_score", sa.Integer(), nullable=True),
        sa.Column(
            "current_stage",
            sa.Enum(
                "NEW",
                "QUALIFYING",
                "PROPOSAL_PHASE",
                "CLOSED_WON",
                "CLOSED_LOST",
                name="leadstage",
            ),
            nullable=False,
        ),
        sa.Column("outcome", sa.Enum("WON", "LOST", name="leadoutcome"), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
        sa.Column(
            "technical_visit_requirement",
            sa.Enum(
                "UNDETERMINED",
                "NOT_REQUIRED",
                "REQUIRED",
                name="technicalvisitrequirement",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "current_stage IN ('NEW', 'QUALIFYING', 'PROPOSAL_PHASE', 'CLOSED_WON', 'CLOSED_LOST')",
            name=op.f("ck_lead_current_stage"),
        ),
        sa.CheckConstraint(
            "interest_type IN ('PHOTOVOLTAIC', 'BESS', 'HIBRID')",
            name=op.f("ck_lead_interest_type"),
        ),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('WON', 'LOST')",
            name=op.f("ck_lead_outcome"),
        ),
        sa.CheckConstraint(
            "technical_visit_requirement IN ('UNDETERMINED', 'NOT_REQUIRED', 'REQUIRED')",
            name=op.f("ck_lead_technical_visit_requirement"),
        ),
        sa.CheckConstraint(
            "qualification_score IS NULL OR (qualification_score >= 0 AND qualification_score <= 100)",
            name=op.f("ck_lead_qualification_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contact.id"], name=op.f("fk_lead_contact_id_contact")
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name=op.f("fk_lead_owner_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead")),
    )
    with op.batch_alter_table("lead", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lead_contact_id"), ["contact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lead_current_stage"), ["current_stage"], unique=False)
        batch_op.create_index(batch_op.f("ix_lead_outcome"), ["outcome"], unique=False)
        batch_op.create_index(batch_op.f("ix_lead_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            "ix_lead_owner_stage_created",
            ["owner_id", "current_stage", "created_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lead_technical_visit_requirement"),
            ["technical_visit_requirement"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_lead_title"), ["title"], unique=False)

    op.create_table(
        "lead_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "original_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("stored_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_lead_document_size_positive")),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["lead.id"], name=op.f("fk_lead_document_lead_id_lead")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["user.id"], name=op.f("fk_lead_document_uploaded_by_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_document")),
    )
    with op.batch_alter_table("lead_document", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lead_document_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(
            "ix_lead_document_lead_uploaded",
            ["lead_id", "uploaded_at", "id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_lead_document_title"), ["title"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lead_document_uploaded_by"), ["uploaded_by"], unique=False
        )

    op.create_table(
        "lead_electricity_bill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "original_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("stored_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_lead_electricity_bill_size_positive")),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["lead.id"], name=op.f("fk_lead_electricity_bill_lead_id_lead")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user.id"],
            name=op.f("fk_lead_electricity_bill_uploaded_by_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_electricity_bill")),
    )
    with op.batch_alter_table("lead_electricity_bill", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lead_electricity_bill_lead_id"), ["lead_id"], unique=False
        )
        batch_op.create_index(
            "ix_lead_electricity_bill_lead_uploaded",
            ["lead_id", "uploaded_at", "id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_lead_electricity_bill_title"), ["title"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lead_electricity_bill_uploaded_by"),
            ["uploaded_by"],
            unique=False,
        )

    op.create_table(
        "lead_interaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column(
            "interaction_type",
            sa.Enum(
                "CALL",
                "EMAIL",
                "MEETING",
                "MESSAGE",
                "NEGOTIATION",
                "NOTE",
                name="leadinteractiontype",
            ),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
        sa.Column("interaction_date", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "interaction_type IN ('CALL', 'EMAIL', 'MEETING', 'MESSAGE', 'NEGOTIATION', 'NOTE')",
            name=op.f("ck_lead_interaction_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
            name=op.f("fk_lead_interaction_created_by_user"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["lead.id"], name=op.f("fk_lead_interaction_lead_id_lead")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_interaction")),
    )
    with op.batch_alter_table("lead_interaction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lead_interaction_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lead_interaction_interaction_date"),
            ["interaction_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lead_interaction_interaction_type"),
            ["interaction_type"],
            unique=False,
        )
        batch_op.create_index(
            "ix_lead_interaction_lead_date",
            ["lead_id", "interaction_date", "id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_lead_interaction_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lead_interaction_title"), ["title"], unique=False)

    op.create_table(
        "proposal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column(
            "installation_address_line",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "installation_city",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=True,
        ),
        sa.Column(
            "installation_state",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=True,
        ),
        sa.Column(
            "installation_postal_code",
            sqlmodel.sql.sqltypes.AutoString(length=30),
            nullable=True,
        ),
        sa.Column("tariff", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("contracted_demand", sa.Float(), nullable=True),
        sa.Column(
            "system_type",
            sa.Enum("PV", "BESS", "HIBRID", name="proposalsystemtype"),
            nullable=True,
        ),
        sa.Column("total_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("annual_savings", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("expected_profit", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column(
            "current_stage",
            sa.Enum(
                "DRAFT",
                "SENT",
                "NEGOTIATION",
                "WON",
                "LOST",
                "SUPERSEDED",
                name="proposalstage",
            ),
            nullable=False,
        ),
        sa.Column("loss_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("proposed_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "current_stage != 'LOST' OR (loss_reason IS NOT NULL AND length(trim(loss_reason)) > 0)",
            name=op.f("ck_proposal_lost_requires_reason"),
        ),
        sa.CheckConstraint(
            "current_stage IN ('DRAFT', 'SENT', 'NEGOTIATION', 'WON', 'LOST', 'SUPERSEDED')",
            name=op.f("ck_proposal_current_stage"),
        ),
        sa.CheckConstraint(
            "system_type IS NULL OR system_type IN ('PV', 'BESS', 'HIBRID')",
            name=op.f("ck_proposal_system_type"),
        ),
        sa.CheckConstraint(
            "annual_savings IS NULL OR annual_savings >= 0",
            name=op.f("ck_proposal_annual_savings_nonnegative"),
        ),
        sa.CheckConstraint(
            "contracted_demand IS NULL OR contracted_demand > 0",
            name=op.f("ck_proposal_contracted_demand_positive"),
        ),
        sa.CheckConstraint(
            "currency IS NULL OR length(currency) = 3",
            name=op.f("ck_proposal_currency_length"),
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name=op.f("ck_proposal_estimated_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "expected_profit IS NULL OR expected_profit >= 0",
            name=op.f("ck_proposal_expected_profit_nonnegative"),
        ),
        sa.CheckConstraint(
            "total_price IS NULL OR total_price > 0",
            name=op.f("ck_proposal_total_price_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name=op.f("fk_proposal_created_by_user")
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], name=op.f("fk_proposal_lead_id_lead")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal")),
    )
    with op.batch_alter_table("proposal", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_proposal_created_by"), ["created_by"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_proposal_current_stage"), ["current_stage"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_proposal_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index("ix_proposal_lead_stage", ["lead_id", "current_stage"], unique=False)
        batch_op.create_index(batch_op.f("ix_proposal_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_proposal_submitted_at"), ["submitted_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_proposal_system_type"), ["system_type"], unique=False)
        batch_op.create_index(
            "ix_proposal_user_stage_created",
            ["created_by", "current_stage", "created_at", "id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_proposal_valid_until"), ["valid_until"], unique=False)
        batch_op.create_index(
            "uq_proposal_one_won_per_lead",
            ["lead_id"],
            unique=True,
            sqlite_where=sa.text("current_stage = 'WON'"),
            postgresql_where=sa.text("current_stage = 'WON'"),
        )

    op.create_table(
        "technical_visit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REQUESTED",
                "SCHEDULED",
                "COMPLETED",
                "CANCELLED",
                name="technicalvisitstatus",
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("receiver_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("receiver_phone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "cancellation_reason",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.CheckConstraint(
            "status != 'CANCELLED' OR cancelled_at IS NOT NULL",
            name=op.f("ck_technical_visit_cancelled_at_required"),
        ),
        sa.CheckConstraint(
            "status != 'COMPLETED' OR completed_at IS NOT NULL",
            name=op.f("ck_technical_visit_completed_at_required"),
        ),
        sa.CheckConstraint(
            "status IN ('REQUESTED', 'SCHEDULED', 'COMPLETED', 'CANCELLED')",
            name=op.f("ck_technical_visit_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name=op.f("fk_technical_visit_created_by_user")
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["lead.id"], name=op.f("fk_technical_visit_lead_id_lead")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technical_visit")),
    )
    with op.batch_alter_table("technical_visit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_technical_visit_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_technical_visit_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(
            "ix_technical_visit_lead_status_scheduled",
            ["lead_id", "status", "scheduled_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_technical_visit_scheduled_at"),
            ["scheduled_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_technical_visit_status"), ["status"], unique=False)

    op.create_table(
        "proposal_bess_system",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("battery_model", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("battery_count", sa.Integer(), nullable=True),
        sa.Column("battery_power_kw", sa.Float(), nullable=True),
        sa.Column("battery_storage_kwh", sa.Float(), nullable=True),
        sa.Column(
            "bess_primary_use",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=True,
        ),
        sa.Column(
            "technical_notes",
            sqlmodel.sql.sqltypes.AutoString(length=4000),
            nullable=True,
        ),
        sa.Column("cost_kwh", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("price_kwh", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.CheckConstraint(
            "battery_count IS NULL OR battery_count >= 0",
            name=op.f("ck_proposal_bess_battery_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "battery_power_kw IS NULL OR battery_power_kw > 0",
            name=op.f("ck_proposal_bess_battery_power_kw_positive"),
        ),
        sa.CheckConstraint(
            "battery_storage_kwh IS NULL OR battery_storage_kwh > 0",
            name=op.f("ck_proposal_bess_battery_storage_kwh_positive"),
        ),
        sa.CheckConstraint(
            "cost_kwh IS NULL OR cost_kwh >= 0",
            name=op.f("ck_proposal_bess_cost_kwh_nonnegative"),
        ),
        sa.CheckConstraint(
            "price_kwh IS NULL OR price_kwh > 0",
            name=op.f("ck_proposal_bess_price_kwh_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.id"],
            name=op.f("fk_proposal_bess_system_proposal_id_proposal"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_bess_system")),
    )
    with op.batch_alter_table("proposal_bess_system", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proposal_bess_system_proposal_id"),
            ["proposal_id"],
            unique=True,
        )

    op.create_table(
        "proposal_commercial_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "original_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("stored_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_proposal_commercial_document_size_positive")
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.id"],
            name=op.f("fk_proposal_commercial_document_proposal_id_proposal"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user.id"],
            name=op.f("fk_proposal_commercial_document_uploaded_by_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_commercial_document")),
    )
    with op.batch_alter_table("proposal_commercial_document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proposal_commercial_document_proposal_id"),
            ["proposal_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_proposal_commercial_document_proposal_uploaded",
            ["proposal_id", "uploaded_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_proposal_commercial_document_title"), ["title"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_proposal_commercial_document_uploaded_by"),
            ["uploaded_by"],
            unique=False,
        )

    op.create_table(
        "proposal_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "classification",
            sa.Enum("COSTS", "TECHNICAL", "OTHER", name="proposaldocumentclassification"),
            nullable=False,
        ),
        sa.Column(
            "original_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("stored_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "classification IN ('COSTS', 'TECHNICAL', 'OTHER')",
            name=op.f("ck_proposal_document_classification"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_proposal_document_size_positive")),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.id"],
            name=op.f("fk_proposal_document_proposal_id_proposal"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user.id"],
            name=op.f("fk_proposal_document_uploaded_by_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_document")),
    )
    with op.batch_alter_table("proposal_document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proposal_document_classification"),
            ["classification"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_proposal_document_proposal_id"),
            ["proposal_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_proposal_document_proposal_uploaded",
            ["proposal_id", "uploaded_at", "id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_proposal_document_title"), ["title"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_proposal_document_uploaded_by"),
            ["uploaded_by"],
            unique=False,
        )

    op.create_table(
        "proposal_pv_system",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("panel_count", sa.Integer(), nullable=True),
        sa.Column("panel_model", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("panel_power", sa.Float(), nullable=True),
        sa.Column(
            "inverter_model",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("inverter_count", sa.Integer(), nullable=True),
        sa.Column("inverter_power", sa.Float(), nullable=True),
        sa.Column(
            "type_of_surface",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=True,
        ),
        sa.Column("total_power_ac", sa.Float(), nullable=True),
        sa.Column("system_size_kw", sa.Float(), nullable=True),
        sa.Column("oversizing_kw", sa.Float(), nullable=True),
        sa.Column("estimated_annual_kwh", sa.Float(), nullable=True),
        sa.Column("estimated_savings_kw", sa.Float(), nullable=True),
        sa.Column(
            "connection_mode",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=True,
        ),
        sa.Column("cost_watt", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("price_watt", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.CheckConstraint(
            "cost_watt IS NULL OR cost_watt >= 0",
            name=op.f("ck_proposal_pv_cost_watt_nonnegative"),
        ),
        sa.CheckConstraint(
            "estimated_annual_kwh IS NULL OR estimated_annual_kwh > 0",
            name=op.f("ck_proposal_pv_estimated_annual_kwh_positive"),
        ),
        sa.CheckConstraint(
            "estimated_savings_kw IS NULL OR estimated_savings_kw >= 0",
            name=op.f("ck_proposal_pv_estimated_savings_kw_nonnegative"),
        ),
        sa.CheckConstraint(
            "inverter_count IS NULL OR inverter_count >= 0",
            name=op.f("ck_proposal_pv_inverter_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "inverter_power IS NULL OR inverter_power > 0",
            name=op.f("ck_proposal_pv_inverter_power_positive"),
        ),
        sa.CheckConstraint(
            "oversizing_kw IS NULL OR oversizing_kw >= 0",
            name=op.f("ck_proposal_pv_oversizing_kw_nonnegative"),
        ),
        sa.CheckConstraint(
            "panel_count IS NULL OR panel_count >= 0",
            name=op.f("ck_proposal_pv_panel_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "panel_power IS NULL OR panel_power > 0",
            name=op.f("ck_proposal_pv_panel_power_positive"),
        ),
        sa.CheckConstraint(
            "price_watt IS NULL OR price_watt > 0",
            name=op.f("ck_proposal_pv_price_watt_positive"),
        ),
        sa.CheckConstraint(
            "system_size_kw IS NULL OR system_size_kw > 0",
            name=op.f("ck_proposal_pv_system_size_kw_positive"),
        ),
        sa.CheckConstraint(
            "total_power_ac IS NULL OR total_power_ac > 0",
            name=op.f("ck_proposal_pv_total_power_ac_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.id"],
            name=op.f("fk_proposal_pv_system_proposal_id_proposal"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_pv_system")),
    )
    with op.batch_alter_table("proposal_pv_system", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proposal_pv_system_proposal_id"),
            ["proposal_id"],
            unique=True,
        )

    op.create_table(
        "proposal_technical_visit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("technical_visit_id", sa.Integer(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "BASED_ON",
                "VALIDATED_BY",
                name="proposaltechnicalvisitrelationshiptype",
            ),
            nullable=False,
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("linked_by", sa.Integer(), nullable=False),
        sa.Column("linked_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "relationship_type IN ('BASED_ON', 'VALIDATED_BY')",
            name=op.f("ck_proposal_technical_visit_relationship_type"),
        ),
        sa.ForeignKeyConstraint(
            ["linked_by"],
            ["user.id"],
            name=op.f("fk_proposal_technical_visit_linked_by_user"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.id"],
            name=op.f("fk_proposal_technical_visit_proposal_id_proposal"),
        ),
        sa.ForeignKeyConstraint(
            ["technical_visit_id"],
            ["technical_visit.id"],
            name=op.f("fk_proposal_technical_visit_technical_visit_id_technical_visit"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_technical_visit")),
        sa.UniqueConstraint(
            "proposal_id", "technical_visit_id", name="uq_proposal_technical_visit_pair"
        ),
    )
    with op.batch_alter_table("proposal_technical_visit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proposal_technical_visit_linked_by"),
            ["linked_by"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_proposal_technical_visit_proposal_id"),
            ["proposal_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_proposal_technical_visit_proposal_linked",
            ["proposal_id", "linked_at", "id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_proposal_technical_visit_relationship_type"),
            ["relationship_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_proposal_technical_visit_technical_visit_id"),
            ["technical_visit_id"],
            unique=False,
        )

    op.create_table(
        "technical_visit_assignee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("visit_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_technical_visit_assignee_user_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["technical_visit.id"],
            name=op.f("fk_technical_visit_assignee_visit_id_technical_visit"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technical_visit_assignee")),
    )
    with op.batch_alter_table("technical_visit_assignee", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_technical_visit_assignee_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_technical_visit_assignee_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_technical_visit_assignee_visit_id"),
            ["visit_id"],
            unique=False,
        )

    op.create_table(
        "technical_visit_attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("visit_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "file_kind",
            sa.Enum("DOCUMENT", "PHOTO", "OTHER", name="technicalvisitattachmentkind"),
            nullable=False,
        ),
        sa.Column(
            "original_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("stored_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "file_kind IN ('DOCUMENT', 'PHOTO', 'OTHER')",
            name=op.f("ck_technical_visit_attachment_file_kind"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_technical_visit_attachment_size_positive")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user.id"],
            name=op.f("fk_technical_visit_attachment_uploaded_by_user"),
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["technical_visit.id"],
            name=op.f("fk_technical_visit_attachment_visit_id_technical_visit"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technical_visit_attachment")),
    )
    with op.batch_alter_table("technical_visit_attachment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_technical_visit_attachment_file_kind"),
            ["file_kind"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_technical_visit_attachment_title"), ["title"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_technical_visit_attachment_uploaded_by"),
            ["uploaded_by"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_technical_visit_attachment_visit_id"),
            ["visit_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_technical_visit_attachment_visit_uploaded",
            ["visit_id", "uploaded_at", "id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("technical_visit_attachment", schema=None) as batch_op:
        batch_op.drop_index("ix_technical_visit_attachment_visit_uploaded")
        batch_op.drop_index(batch_op.f("ix_technical_visit_attachment_visit_id"))
        batch_op.drop_index(batch_op.f("ix_technical_visit_attachment_uploaded_by"))
        batch_op.drop_index(batch_op.f("ix_technical_visit_attachment_title"))
        batch_op.drop_index(batch_op.f("ix_technical_visit_attachment_file_kind"))

    op.drop_table("technical_visit_attachment")
    with op.batch_alter_table("technical_visit_assignee", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technical_visit_assignee_visit_id"))
        batch_op.drop_index(batch_op.f("ix_technical_visit_assignee_user_id"))
        batch_op.drop_index(batch_op.f("ix_technical_visit_assignee_name"))

    op.drop_table("technical_visit_assignee")
    with op.batch_alter_table("proposal_technical_visit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposal_technical_visit_technical_visit_id"))
        batch_op.drop_index(batch_op.f("ix_proposal_technical_visit_relationship_type"))
        batch_op.drop_index("ix_proposal_technical_visit_proposal_linked")
        batch_op.drop_index(batch_op.f("ix_proposal_technical_visit_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_proposal_technical_visit_linked_by"))

    op.drop_table("proposal_technical_visit")
    with op.batch_alter_table("proposal_pv_system", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposal_pv_system_proposal_id"))

    op.drop_table("proposal_pv_system")
    with op.batch_alter_table("proposal_document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposal_document_uploaded_by"))
        batch_op.drop_index(batch_op.f("ix_proposal_document_title"))
        batch_op.drop_index("ix_proposal_document_proposal_uploaded")
        batch_op.drop_index(batch_op.f("ix_proposal_document_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_proposal_document_classification"))

    op.drop_table("proposal_document")
    with op.batch_alter_table("proposal_commercial_document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposal_commercial_document_uploaded_by"))
        batch_op.drop_index(batch_op.f("ix_proposal_commercial_document_title"))
        batch_op.drop_index("ix_proposal_commercial_document_proposal_uploaded")
        batch_op.drop_index(batch_op.f("ix_proposal_commercial_document_proposal_id"))

    op.drop_table("proposal_commercial_document")
    with op.batch_alter_table("proposal_bess_system", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposal_bess_system_proposal_id"))

    op.drop_table("proposal_bess_system")
    with op.batch_alter_table("technical_visit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technical_visit_status"))
        batch_op.drop_index(batch_op.f("ix_technical_visit_scheduled_at"))
        batch_op.drop_index("ix_technical_visit_lead_status_scheduled")
        batch_op.drop_index(batch_op.f("ix_technical_visit_lead_id"))
        batch_op.drop_index(batch_op.f("ix_technical_visit_created_by"))

    op.drop_table("technical_visit")
    with op.batch_alter_table("proposal", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_proposal_one_won_per_lead",
            sqlite_where=sa.text("current_stage = 'WON'"),
            postgresql_where=sa.text("current_stage = 'WON'"),
        )
        batch_op.drop_index(batch_op.f("ix_proposal_valid_until"))
        batch_op.drop_index("ix_proposal_user_stage_created")
        batch_op.drop_index(batch_op.f("ix_proposal_system_type"))
        batch_op.drop_index(batch_op.f("ix_proposal_submitted_at"))
        batch_op.drop_index(batch_op.f("ix_proposal_name"))
        batch_op.drop_index("ix_proposal_lead_stage")
        batch_op.drop_index(batch_op.f("ix_proposal_lead_id"))
        batch_op.drop_index(batch_op.f("ix_proposal_current_stage"))
        batch_op.drop_index(batch_op.f("ix_proposal_created_by"))

    op.drop_table("proposal")
    with op.batch_alter_table("lead_interaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lead_interaction_title"))
        batch_op.drop_index(batch_op.f("ix_lead_interaction_lead_id"))
        batch_op.drop_index("ix_lead_interaction_lead_date")
        batch_op.drop_index(batch_op.f("ix_lead_interaction_interaction_type"))
        batch_op.drop_index(batch_op.f("ix_lead_interaction_interaction_date"))
        batch_op.drop_index(batch_op.f("ix_lead_interaction_created_by"))

    op.drop_table("lead_interaction")
    with op.batch_alter_table("lead_electricity_bill", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lead_electricity_bill_uploaded_by"))
        batch_op.drop_index(batch_op.f("ix_lead_electricity_bill_title"))
        batch_op.drop_index("ix_lead_electricity_bill_lead_uploaded")
        batch_op.drop_index(batch_op.f("ix_lead_electricity_bill_lead_id"))

    op.drop_table("lead_electricity_bill")
    with op.batch_alter_table("lead_document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lead_document_uploaded_by"))
        batch_op.drop_index(batch_op.f("ix_lead_document_title"))
        batch_op.drop_index("ix_lead_document_lead_uploaded")
        batch_op.drop_index(batch_op.f("ix_lead_document_lead_id"))

    op.drop_table("lead_document")
    with op.batch_alter_table("lead", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lead_title"))
        batch_op.drop_index(batch_op.f("ix_lead_technical_visit_requirement"))
        batch_op.drop_index("ix_lead_owner_stage_created")
        batch_op.drop_index(batch_op.f("ix_lead_owner_id"))
        batch_op.drop_index(batch_op.f("ix_lead_outcome"))
        batch_op.drop_index(batch_op.f("ix_lead_current_stage"))
        batch_op.drop_index(batch_op.f("ix_lead_contact_id"))

    op.drop_table("lead")
    with op.batch_alter_table("individual_contact_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_individual_contact_profile_email"))
        batch_op.drop_index(batch_op.f("ix_individual_contact_profile_contact_id"))

    op.drop_table("individual_contact_profile")
    with op.batch_alter_table("company_contact_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_company_contact_profile_contact_id"))

    op.drop_table("company_contact_profile")
    with op.batch_alter_table("company_contact_person", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_company_contact_person_name"))
        batch_op.drop_index(batch_op.f("ix_company_contact_person_email"))
        batch_op.drop_index(batch_op.f("ix_company_contact_person_company_contact_id"))

    op.drop_table("company_contact_person")
    with op.batch_alter_table("contact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_type"))
        batch_op.drop_index(batch_op.f("ix_contact_promoter_id"))
        batch_op.drop_index(batch_op.f("ix_contact_owner_id"))
        batch_op.drop_index(batch_op.f("ix_contact_name"))

    op.drop_table("contact")
    with op.batch_alter_table("stage_transition", schema=None) as batch_op:
        batch_op.drop_index("ix_stage_transition_user_time")
        batch_op.drop_index(batch_op.f("ix_stage_transition_transitioned_by"))
        batch_op.drop_index(batch_op.f("ix_stage_transition_transitioned_at"))
        batch_op.drop_index(batch_op.f("ix_stage_transition_entity_type"))
        batch_op.drop_index("ix_stage_transition_entity_time")
        batch_op.drop_index(batch_op.f("ix_stage_transition_entity_id"))

    op.drop_table("stage_transition")
    with op.batch_alter_table("promoter", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_promoter_owner_id"))
        batch_op.drop_index(batch_op.f("ix_promoter_name"))

    op.drop_table("promoter")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
