export { useLeadList, useLead, useLeadDocuments, useLeadElectricityBills, useLeadInteractions } from './queries/useLeads'
export {
  useCreateLead,
  useUpdateLead,
  useDeleteLead,
  useMoveLeadStage,
  useCloseLead,
  useUploadLeadDocument,
  useDeleteLeadDocument,
  useUploadLeadElectricityBill,
  useDeleteLeadElectricityBill,
  useCreateLeadInteraction,
  useUpdateLeadInteraction,
  useDeleteLeadInteraction,
} from './mutations/useLeadMutations'
export type {
  LeadRead,
  LeadCreate,
  LeadUpdate,
  LeadClose,
  LeadStageChange,
  LeadFilters,
  LeadStage,
  LeadOutcome,
  LeadInterestType,
  LeadInteractionType,
  LeadDocumentRead,
  LeadElectricityBillRead,
  LeadInteractionCreate,
  LeadInteractionUpdate,
  LeadInteractionRead,
} from './types'
export {
  LEAD_STAGES,
  LEAD_OUTCOMES,
  LEAD_INTEREST_TYPES,
  LEAD_INTERACTION_TYPES,
  STAGE_LABELS,
  STAGE_VARIANTS,
  INTEREST_LABELS,
  INTERACTION_LABELS,
} from './types'
